MUNICIPIOS_ANTIOQUIA = [
    # Área Metropolitana del Valle de Aburrá
    ('Medellín', 'Medellín'),
    ('Bello', 'Bello'),
    ('Barbosa', 'Barbosa'),
    ('Caldas', 'Caldas'),
    ('Copacabana', 'Copacabana'),
    ('Envigado', 'Envigado'),
    ('Girardota', 'Girardota'),
    ('Itagüí', 'Itagüí'),
    ('La Estrella', 'La Estrella'),
    ('Sabaneta', 'Sabaneta'),
    
    # Oriente
    ('Abejorral', 'Abejorral'),
    ('Alejandría', 'Alejandría'),
    ('Argelia', 'Argelia'),
    ('Carmen de Viboral', 'Carmen de Viboral'),
    ('Cocorná', 'Cocorná'),
    ('Concepción', 'Concepción'),
    ('El Peñol', 'El Peñol'),
    ('El Retiro', 'El Retiro'),
    ('El Santuario', 'El Santuario'),
    ('Granada', 'Granada'),
    ('Guarne', 'Guarne'),
    ('Guatapé', 'Guatapé'),
    ('La Ceja', 'La Ceja'),
    ('La Unión', 'La Unión'),
    ('Marinilla', 'Marinilla'),
    ('Nariño', 'Nariño'),
    ('Rionegro', 'Rionegro'),
    ('San Carlos', 'San Carlos'),
    ('San Francisco', 'San Francisco'),
    ('San Luis', 'San Luis'),
    ('San Rafael', 'San Rafael'),
    ('San Vicente', 'San Vicente'),
    ('Sonsón', 'Sonsón'),
    
    # Norte
    ('Amalfi', 'Amalfi'),
    ('Angostura', 'Angostura'),
    ('Anorí', 'Anorí'),
    ('Belmira', 'Belmira'),
    ('Briceño', 'Briceño'),
    ('Campamento', 'Campamento'),
    ('Carolina', 'Carolina'),
    ('Donmatías', 'Donmatías'),
    ('Entrerríos', 'Entrerríos'),
    ('Gómez Plata', 'Gómez Plata'),
    ('Guadalupe', 'Guadalupe'),
    ('Ituango', 'Ituango'),
    ('Remedios', 'Remedios'),
    ('San Andrés de Cuerquia', 'San Andrés de Cuerquia'),
    ('San José de la Montaña', 'San José de la Montaña'),
    ('San Pedro de los Milagros', 'San Pedro de los Milagros'),
    ('Santa Rosa de Osos', 'Santa Rosa de Osos'),
    ('Santo Domingo', 'Santo Domingo'),
    ('Segovia', 'Segovia'),
    ('Toledo', 'Toledo'),
    ('Valdivia', 'Valdivia'),
    ('Yarumal', 'Yarumal'),
    ('Yolombó', 'Yolombó'),
    ('Yalí', 'Yalí'),
    
    # Nordeste
    ('Cisneros', 'Cisneros'),
    ('Maceo', 'Maceo'),
    ('Puerto Berrío', 'Puerto Berrío'),
    ('Puerto Nare', 'Puerto Nare'),
    ('Puerto Triunfo', 'Puerto Triunfo'),
    ('Yondó', 'Yondó'),
    
    # Bajo Cauca
    ('Cáceres', 'Cáceres'),
    ('Caucasia', 'Caucasia'),
    ('El Bagre', 'El Bagre'),
    ('Nechí', 'Nechí'),
    ('Tarazá', 'Tarazá'),
    ('Zaragoza', 'Zaragoza'),
    
    # Magdalena Medio
    ('Caracolí', 'Caracolí'),
    ('Maceo', 'Maceo'),
    ('Puerto Berrío', 'Puerto Berrío'),
    ('Puerto Nare', 'Puerto Nare'),
    ('Puerto Triunfo', 'Puerto Triunfo'),
    ('Yondó', 'Yondó'),
    
    # Occidente
    ('Abriaquí', 'Abriaquí'),
    ('Anzá', 'Anzá'),
    ('Armenia', 'Armenia'),
    ('Buriticá', 'Buriticá'),
    ('Caicedo', 'Caicedo'),
    ('Cañasgordas', 'Cañasgordas'),
    ('Dabeiba', 'Dabeiba'),
    ('Ebéjico', 'Ebéjico'),
    ('Frontino', 'Frontino'),
    ('Giraldo', 'Giraldo'),
    ('Heliconia', 'Heliconia'),
    ('Liborina', 'Liborina'),
    ('Olaya', 'Olaya'),
    ('Peque', 'Peque'),
    ('Sabanalarga', 'Sabanalarga'),
    ('San Jerónimo', 'San Jerónimo'),
    ('Santa Fe de Antioquia', 'Santa Fe de Antioquia'),
    ('Sopetrán', 'Sopetrán'),
    ('Uramita', 'Uramita'),
    
    # Suroeste
    ('Amagá', 'Amagá'),
    ('Andes', 'Andes'),
    ('Angelópolis', 'Angelópolis'),
    ('Betania', 'Betania'),
    ('Betulia', 'Betulia'),
    ('Caramanta', 'Caramanta'),
    ('Ciudad Bolívar', 'Ciudad Bolívar'),
    ('Concordia', 'Concordia'),
    ('Fredonia', 'Fredonia'),
    ('Hispania', 'Hispania'),
    ('Jericó', 'Jericó'),
    ('La Pintada', 'La Pintada'),
    ('Montebello', 'Montebello'),
    ('Pueblorrico', 'Pueblorrico'),
    ('Salgar', 'Salgar'),
    ('Santa Bárbara', 'Santa Bárbara'),
    ('Támesis', 'Támesis'),
    ('Tarso', 'Tarso'),
    ('Titiribí', 'Titiribí'),
    ('Urrao', 'Urrao'),
    ('Valparaíso', 'Valparaíso'),
    ('Venecia', 'Venecia'),
    
    # Urabá
    ('Apartadó', 'Apartadó'),
    ('Arboletes', 'Arboletes'),
    ('Carepa', 'Carepa'),
    ('Chigorodó', 'Chigorodó'),
    ('Murindó', 'Murindó'),
    ('Mutatá', 'Mutatá'),
    ('Necoclí', 'Necoclí'),
    ('San Juan de Urabá', 'San Juan de Urabá'),
    ('San Pedro de Urabá', 'San Pedro de Urabá'),
    ('Turbo', 'Turbo'),
    ('Vigía del Fuerte', 'Vigía del Fuerte'),
]