# Generated by Django 5.2 on 2025-09-10 00:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_alter_ubicacionvendedor_departamento_and_more'),
        ('productos', '0002_remove_producto_imagen_url_producto_imagen'),
        ('reseñas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reseña',
            options={'verbose_name': 'Reseña', 'verbose_name_plural': 'Reseñas'},
        ),
        migrations.AlterField(
            model_name='reseña',
            name='calificacion',
            field=models.IntegerField(help_text='Calificación de 1 a 5 estrellas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='reseña',
            name='contenido',
            field=models.TextField(blank=True, help_text='Comentario opcional sobre el producto', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='reseña',
            unique_together={('producto', 'cliente')},
        ),
    ]
