# Generated by Django 5.2.6 on 2025-09-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentavendedor',
            name='nombre_tienda',
            field=models.CharField(default='Mi Tienda', max_length=150),
        ),
    ]
