# Generated by Django 5.2 on 2025-09-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_cuentavendedor_nombre_tienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacionvendedor',
            name='departamento',
            field=models.CharField(default='Antioquia', max_length=50),
        ),
        migrations.AlterField(
            model_name='ubicacionvendedor',
            name='descripcion_zona',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ubicacionvendedor',
            name='municipio',
            field=models.CharField(max_length=50),
        ),
    ]
